server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Jianye@100
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 修正扫描路径，匹配java下打包后的mapper目录
  mapper-locations: classpath:com/library/mapper/*.xml
  configuration:
    # 下划线自动转驼峰（book_status → bookStatus）
    map-underscore-to-camel-case: true

# PageHelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql